from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, ClassVar, Dict, List, Optional


class VectorStore(ABC):
    """
    Abstract base class for a vector store provider.

    This interface defines the basic methods for adding, deleting, and searching
    vector embeddings with optional metadata filtering.
    """

    support_store_texts: ClassVar[Optional[bool]] = None

    def __init_subclass__(cls) -> None:
        super().__init_subclass__()
        if cls.support_store_texts is None:
            raise TypeError(
                f"Class {cls.__name__} must define 'support_store_texts' class attribute"
            )

    @abstractmethod
    def add_vectors(
        self,
        vectors: List[List[float]],
        ids: Optional[List[str]] = None,
        metadatas: Optional[List[Dict[str, Any]]] = None,
    ) -> List[str]:
        """
        Add vectors to the store.

        Args:
            vectors: List of vectors to add.
            ids: Optional list of IDs for each vector. If not provided, IDs should be autogenerated.
            metadatas: Optional list of metadata dicts associated with each vector.

        Returns:
            List of vector IDs stored in the vector store.
        """
        pass

    @abstractmethod
    def delete_vectors(self, ids: List[str]) -> bool:
        """
        Delete vectors from the store by their IDs.

        Args:
            ids: List of vector IDs to delete.

        Returns:
            True if deletion was successful, False otherwise.
        """
        pass

    @abstractmethod
    def search_vectors(
        self,
        query_vector: List[float],
        top_k: int = 5,
        filters: Optional[Dict[str, Any]] = None,
    ) -> List[Dict[str, Any]]:
        """
        Search for vectors similar to the query vector.

        Args:
            query_vector: Vector to search for.
            top_k: Number of top similar vectors to return.
            filters: Optional metadata filters to narrow search results.

        Returns:
            List of dictionaries each containing at least 'id' and 'score' keys,
            optionally including 'metadata'.
        """
        pass

    @abstractmethod
    def clear(self) -> None:
        """
        Clear all vectors and metadata from the store.
        """
        pass
